#!/usr/bin/env python
"""Train a deep hedging model on synthetic data generated by FinDiffusion.

The model learns to hedge a European call option (5% OTM, 30-day TTL) by
minimising the CVaR of hedging errors on synthetic price paths.
"""

import argparse
import logging
import sys
from pathlib import Path

import numpy as np
import torch
import yaml
import matplotlib.pyplot as plt

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.models import FinancialDiffusion
from src.data import FinancialDataModule
from src.hedging import DeepHedger, HedgingTrainer

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

S0 = 100.0
OTM_FACTOR = 1.05   # strike = S0 * 1.05 (5% out of the money)
TTL = 30            # trading days


def load_diffusion_model(checkpoint_path: str, config_path: str, device: torch.device):
    with open(config_path) as f:
        config = yaml.safe_load(f)
    ckpt = torch.load(checkpoint_path, map_location=device)
    model = FinancialDiffusion(
        seq_len=config["data"]["seq_len"],
        input_dim=config["model"]["input_dim"],
        d_model=config["model"]["d_model"],
        n_layers=config["model"]["n_layers"],
        n_heads=config["model"]["n_heads"],
        d_ff=config["model"]["d_ff"],
        d_cond=config["model"]["condition_dim"],
        n_regimes=config["model"]["n_regimes"],
        timesteps=config["model"]["timesteps"],
        beta_schedule=config["model"]["beta_schedule"],
        beta_start=config["model"]["beta_start"],
        beta_end=config["model"]["beta_end"],
        prediction_type=config["model"]["prediction_type"],
        dropout=config["model"]["dropout"],
    )
    model.load_state_dict(ckpt["model_state_dict"])
    model.to(device)
    model.eval()

    data_module = FinancialDataModule(
        tickers=config["data"]["tickers"],
        start_date=config["data"]["start_date"],
        end_date=config["data"]["end_date"],
        seq_len=config["data"]["seq_len"],
        stride=config["data"]["stride"],
        train_ratio=config["data"]["train_ratio"],
        val_ratio=config["data"]["val_ratio"],
        batch_size=config["evaluation"]["batch_size"],
        data_dir=config["paths"]["data_dir"],
    )
    data_module.setup()
    return model, data_module


@torch.no_grad()
def generate_synthetic_returns(
    model: FinancialDiffusion,
    data_module: FinancialDataModule,
    n_samples: int,
    device: torch.device,
) -> np.ndarray:
    """Generate diverse synthetic log-return paths (unconditional).

    Returns: (N, seq_len) float32 array of raw log returns.
    """
    samples = model.generate(n_samples=n_samples, device=device, progress=True)
    samples = samples.cpu().numpy()                    # (N, seq_len, 1) or (N, seq_len)
    samples = data_module.denormalize(samples)
    if samples.ndim == 3:
        samples = samples[:, :, 0]
    return samples.astype(np.float32)


def main():
    parser = argparse.ArgumentParser(
        description="Train deep hedging model on FinDiffusion synthetic data",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--checkpoint", type=str, required=True, help="FinDiffusion checkpoint")
    parser.add_argument("--config",     type=str, default="configs/default.yaml")
    parser.add_argument("--n_samples",  type=int, default=10000, help="Synthetic training paths")
    parser.add_argument("--n_epochs",   type=int, default=100)
    parser.add_argument("--batch_size", type=int, default=256)
    parser.add_argument("--lr",         type=float, default=1e-3)
    parser.add_argument("--hidden_dim", type=int, default=64)
    parser.add_argument("--cvar_alpha", type=float, default=0.95)
    parser.add_argument("--output_dir", type=str, default="outputs/hedging")
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Device: {device}")

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    strike = S0 * OTM_FACTOR
    logger.info(f"Option: European call  S0={S0}  K={strike:.1f} ({(OTM_FACTOR-1):.0%} OTM)  T={TTL} days")

    # --- Generate synthetic training data ---
    logger.info(f"Loading FinDiffusion from {args.checkpoint} ...")
    diff_model, data_module = load_diffusion_model(args.checkpoint, args.config, device)

    logger.info(f"Generating {args.n_samples} synthetic paths ...")
    log_returns = generate_synthetic_returns(diff_model, data_module, args.n_samples, device)
    logger.info(f"Synthetic data shape: {log_returns.shape}")

    # --- Build and train hedging model ---
    hedger = DeepHedger(input_dim=2, hidden_dim=args.hidden_dim)
    logger.info(f"DeepHedger parameters: {sum(p.numel() for p in hedger.parameters()):,}")

    trainer = HedgingTrainer(
        model=hedger,
        strike=strike,
        seq_len=TTL,
        lr=args.lr,
        cvar_alpha=args.cvar_alpha,
        device=device,
    )

    logger.info("Training ...")
    losses = trainer.train(
        synthetic_log_returns=log_returns,
        n_epochs=args.n_epochs,
        batch_size=args.batch_size,
        checkpoint_path=output_dir / "hedging_model.pt",
        s0=S0,
    )

    # --- Training curve ---
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(losses)
    ax.set_xlabel("Epoch")
    ax.set_ylabel(f"CVaR({args.cvar_alpha:.0%}) Loss")
    ax.set_title("Deep Hedging — Training Loss (Synthetic Data)")
    plt.tight_layout()
    plt.savefig(output_dir / "training_loss.png", dpi=150)
    plt.close()

    logger.info(f"Best model saved to {output_dir}/hedging_model.pt")
    logger.info("Done.")


if __name__ == "__main__":
    main()
